In [1]:
# Numpy  is Numerical Python
# Numpy deals with arrays
# arrays ? ndim arrays ??

# list vs Numpy

In [2]:
a1 = [1,2,3,4,5,6,7,8,9,10]
a1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
for i in a1:
    print(i*i)

1
4
9
16
25
36
49
64
81
100


In [5]:
a2 = [i*i for i in a1  ]

In [6]:
print(a2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [7]:
a2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [8]:
# using numpy to do the same operation 
# elementwise operation

In [21]:
# a1 = [1,2,3,4,5,6,7,8,9,10]
# a1*a1

In [12]:
import numpy as np

In [14]:
arr1 = np.array(a1)

In [15]:
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
print(type(arr1))

<class 'numpy.ndarray'>


In [18]:
arr1**2 ## elementwise operation possible now 

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [19]:
arr1*arr1

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [22]:
arr1*arr1*arr1

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

# faster operations

In [26]:
a1 = list(range(10000))

In [27]:
ans = [i*i for i in a1  ]

In [36]:
# print(ans)

In [30]:
%timeit [i*i for i in a1  ]

746 µs ± 135 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [32]:
# testing time execution for numpy

In [33]:
i = np.arange(10000)

In [34]:
print(i)

[   0    1    2 ... 9997 9998 9999]


In [38]:
%timeit (i*i)

10.4 µs ± 1.58 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [39]:
# revision
arr2 = np.array([11,22,33,44,55,66])

In [41]:
print(type(arr2))

<class 'numpy.ndarray'>


In [43]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])