#  array creation

In [4]:
import numpy as np

In [8]:
arr1 = np.arange(12)

In [9]:
arr1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
arr1.ndim

1

# creating 2D Array

In [36]:
#  using list of lists

In [11]:
m = ([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [12]:
m

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]]

In [13]:
print(type(m))

<class 'list'>


In [15]:
m_arr = np.array(m)

In [17]:
m_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [18]:
m_arr.shape

(2, 12)

In [19]:
m_arr.size

24

In [20]:
m_arr.ndim

2

In [21]:
arr2 = np.arange(12)

In [22]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
# using reshape() to change the array from 1D to 2D
#  can also be changed to higher Dimensions

In [23]:
arr2.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
arr2.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
arr3 = np.linspace(1,12,15).reshape(3,5)

In [28]:
arr3

array([[ 1.        ,  1.78571429,  2.57142857,  3.35714286,  4.14285714],
       [ 4.92857143,  5.71428571,  6.5       ,  7.28571429,  8.07142857],
       [ 8.85714286,  9.64285714, 10.42857143, 11.21428571, 12.        ]])

In [29]:
arr3.shape

(3, 5)

In [30]:
arr3.ndim

2

In [31]:
arr3.size

15

In [ ]:
# 1D will have one [] 
# 2d will have [[ ]]
# 3d will have [[[ ]]]
# thus by counting the opening square brackets we can clerly identify the Dimanesion of array

In [32]:
arr4 = np.arange(12)

In [33]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
arr4 = np.arange(12).reshape(3,4)

In [35]:
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])