# Aggreagte Function

In [2]:
import numpy as np

In [3]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,5])

In [5]:
a+b #universal function , ufunc

array([12, 24, 36, 48, 60])

In [6]:
np.sum(a)

165

In [7]:
np.sum(b)

15

In [8]:
np.mean(a)

33.0

In [9]:
np.min(a)

11

In [10]:
np.max(a)

55

In [11]:
# on 2d arrays

In [14]:
arr1 =  np.arange(10,60,2).reshape(5,5)

In [15]:
arr1

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [16]:
np.sum(arr1)

850

In [17]:
np.sum(arr1,axis=1)

array([ 70, 120, 170, 220, 270])

In [19]:
np.sum(arr1,axis=0)

array([150, 160, 170, 180, 190])

In [20]:
np.max(arr1,axis=0)

array([50, 52, 54, 56, 58])

In [21]:
np.max(arr1,axis=1)

array([18, 28, 38, 48, 58])

In [22]:
score = np.random.randint(10,100,15).reshape(5,3)

In [23]:
score

array([[17, 82, 40],
       [78, 66, 46],
       [94, 62, 47],
       [35, 26, 44],
       [34, 95, 44]])

In [24]:
np.max(score,axis=1)

array([82, 78, 94, 44, 95])

In [25]:
np.max(score,axis=0)

array([94, 95, 47])

In [28]:
np.mean(score,axis=1)

array([46.33333333, 63.33333333, 67.66666667, 35.        , 57.66666667])

In [29]:
np.min(score,axis=0)

array([17, 26, 40])

In [30]:
np.sum(score,axis=1) #top to bottom : axis = 0 , left to right : axis = 1

array([139, 190, 203, 105, 173])

In [32]:
np.sum(score,axis=1)[4]

173

# Logical Fun

In [33]:
# any 
# all
# True and False

In [44]:
score = np.random.randint(0,100,15).reshape(5,3)

In [45]:
score

array([[96,  6,  3],
       [ 6,  9, 10],
       [40, 47, 70],
       [57, 70, 81],
       [ 6, 80, 20]])

In [46]:
arr2 = np.array([11,22,22,0,14,36])

In [47]:
arr2

array([11, 22, 22,  0, 14, 36])

In [48]:
np.any(arr2)

True

In [49]:
arr2 = np.array([0,0,0,0,0,36])

In [50]:
np.any(arr2)

True

In [51]:
arr2 = np.array([0,0,0,0,0,0])

In [52]:
np.any(arr2) #only when all the elemets are ZERO

False

In [ ]:
# all

In [54]:
arr2 = np.array([11,22,0,4,36])

In [55]:
np.all(arr2)

False

In [62]:
arr2 = np.array([0,0,0])

In [63]:
np.all(arr2)

False

In [64]:
a = np.array([44,88,44,22,55,44])
b = np.array([77,55,14,25,36,36])

In [65]:
a>b

array([False,  True,  True, False,  True,  True])

In [66]:
np.any(a>b) #any one True is required

True

In [67]:
np.all(a>b) #only for all True values : o/p will be True

False

In [68]:
a = np.array([44,88])
b = np.array([1,2])

In [69]:
a>b

array([ True,  True])

In [70]:
np.any(a>b)

True

In [74]:
np.any(a<b) #since both values are False

False

In [71]:
np.all(a>b)

True

In [72]:
np.all(a<b)

False

In [75]:
a = np.array([44,88,44,22,55,44])
b = np.array([77,55,14,25,36,36])

In [76]:
np.sort(a)

array([22, 44, 44, 44, 55, 88])

In [80]:
np.sort(b)

array([14, 25, 36, 36, 55, 77])

In [81]:
np.argsort(a)#it will give array of the index position of the sorted array values

array([3, 0, 2, 5, 4, 1], dtype=int64)

# Broadcasting

# Splitting

# Copies and Views