# Broadcasting

In [2]:
import numpy as np

In [9]:
x = np.array([10,20,30])
y = np.array([[1],[2],[3],[4]])

In [10]:
x

array([10, 20, 30])

In [11]:
print(x.shape,x.ndim)

(3,) 1


In [12]:
y

array([[1],
       [2],
       [3],
       [4]])

In [13]:
print(y.ndim,y.shape)

2 (4, 1)


In [14]:
x+y

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [15]:
z = np.array([10,20,30,40,50])
z * 5

array([ 50, 100, 150, 200, 250])

# splitting

In [16]:
x = np.arange(9)

In [17]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
np.split(x,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [20]:
np.split(x,3)[1] #selecting from the result after splitting 

array([3, 4, 5])

In [21]:
# splitting a 2d array

In [22]:
x = np.arange(16).reshape(4,4)

In [23]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
np.split(x,4,axis=0) #default by axis  = ?

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [26]:
np.split(x,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [27]:
np.split(x,4,axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [28]:
x = np.arange(10)

In [29]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# np.split(x,3) #error : equal division

In [34]:
y = np.arange(16).reshape(4,4)

In [35]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
np.vsplit(y,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [37]:
np.hsplit(y ,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# copies and views

In [49]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [50]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
b = a 

In [52]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
print(id(a))
print(id(b))

2665372493552
2665372493552


In [44]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
del a

In [55]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
# deep copy

In [47]:
c =  a.copy()

In [48]:
print(id(a))
print(id(c))

2665372492016
2665375092432
