In [1]:
import numpy as np

In [6]:
data = np.loadtxt('fitbit.txt',dtype='str')

In [7]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [8]:
print(type(data))

<class 'numpy.ndarray'>


In [9]:
data.shape

(26, 7)

In [10]:
data[0]

array(['06-10-2017', '5464', '200', '181', '6', '0', '68'], dtype='<U10')

In [11]:
data[1]

array(['07-10-2017', '7167', '200', '208', '6', '0', '68'], dtype='<U10')

# Data cleaning

In [12]:
# data has no header
# data is in the form of string , cant be numerically compared

In [13]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017'],
       ['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
        '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
        '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
        '6347', '5911'],
       ['200', '200', '300', '100', '300', '300', '100', '200', '200',
        '300', '300', '300', '300', '200', '200', '200', '300', '300',
        '100', '100', '300', '300', '300', '100', '200', '200'],
       ['181', '208', '341', '190', '307', '302', '198', '201', '195',
        '327', '331', '318', '344', '204', '180', '201', '32

In [14]:
date ,step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg = data.T

In [15]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [16]:
step_count

array(['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
       '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
       '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
       '6347', '5911'], dtype='<U10')

In [17]:
# changing the string data type to 'int'

In [18]:
step_count.dtype

dtype('<U10')

In [21]:
step_count = np.array(step_count,dtype='int')

In [22]:
calories_burned = np.array(calories_burned,dtype='int')
hours_of_sleep = np.array(hours_of_sleep,dtype='int')
weight_kg  = np.array(weight_kg,dtype='int')

In [20]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [23]:
weight_kg

array([68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68])

In [25]:
calories_burned.dtype

dtype('int32')

In [26]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [27]:
np.unique(mood) #this is not a numerical data but is a categorical data 

array(['100', '200', '300'], dtype='<U10')

In [28]:
# 100 = sad
# 200 =  neutral
# 300 = happy

In [30]:
mood == '100'

array([False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False,  True, False, False])

In [36]:
mood[mood == '100'] = 'sad'

In [31]:
mood == '200'

array([ True,  True, False, False, False, False, False,  True,  True,
       False, False, False, False,  True,  True,  True, False, False,
       False, False, False, False, False, False,  True,  True])

In [38]:
mood[mood == '200'] ='neutral'

In [32]:
mood == '300'

array([False, False,  True, False,  True,  True, False, False, False,
        True,  True,  True,  True, False, False, False,  True,  True,
       False, False,  True,  True,  True, False, False, False])

In [39]:
mood[mood == '300'] = 'hapyy'

In [40]:
mood

array(['neutral', 'neutral', 'hapyy', 'sad', 'hapyy', 'hapyy', 'sad',
       'neutral', 'neutral', 'hapyy', 'hapyy', 'hapyy', 'hapyy',
       'neutral', 'neutral', 'neutral', 'hapyy', 'hapyy', 'sad', 'sad',
       'hapyy', 'hapyy', 'hapyy', 'sad', 'neutral', 'neutral'],
      dtype='<U10')

# data Analysing

In [41]:
data

array([['06-10-2017', '5464', 'neutral', '181', '6', '0', '68'],
       ['07-10-2017', '7167', 'neutral', '208', '6', '0', '68'],
       ['08-10-2017', '9874', 'hapyy', '341', '5', '0', '68'],
       ['09-10-2017', '4969', 'sad', '190', '8', '0', '68'],
       ['10-10-2017', '8538', 'hapyy', '307', '5', '0', '68'],
       ['11-10-2017', '9875', 'hapyy', '302', '5', '0', '68'],
       ['12-10-2017', '4662', 'sad', '198', '8', '0', '68'],
       ['13-10-2017', '6310', 'neutral', '201', '6', '0', '68'],
       ['14-10-2017', '7556', 'neutral', '195', '6', '0', '68'],
       ['15-10-2017', '9073', 'hapyy', '327', '5', '0', '68'],
       ['16-10-2017', '9690', 'hapyy', '331', '5', '0', '68'],
       ['17-10-2017', '9146', 'hapyy', '318', '5', '0', '68'],
       ['18-10-2017', '9752', 'hapyy', '344', '5', '0', '68'],
       ['19-10-2017', '6974', 'neutral', '204', '6', '0', '68'],
       ['20-10-2017', '5619', 'neutral', '180', '6', '0', '68'],
       ['21-10-2017', '6889', 'neutral', '201',

In [42]:
# max steps count

In [44]:
np.max(step_count)

9875

In [45]:
np.mean(step_count)

7344.461538461538

In [46]:
np.argmax(step_count)

5

In [47]:
# data on which max steps done

In [48]:
date[5]

'11-10-2017'

In [51]:
# feq of mood

In [52]:
len(mood[mood == 'sad'])

5

In [53]:
len(mood[mood == 'neutral'])

9

In [55]:
len(mood[mood == 'hapyy'])

12

In [56]:
np.unique(mood)

array(['hapyy', 'neutral', 'sad'], dtype='<U10')

In [57]:
np.unique(mood,return_counts=True)

(array(['hapyy', 'neutral', 'sad'], dtype='<U10'),
 array([12,  9,  5], dtype=int64))